on: [push]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
        -   name: Hello world action step
            id: hello
            uses: Saw-mon-and-Natalie/hello-world-docker-action@v1.0.1
            with:
                who-to-greet: 'Mona the Octocat'
        -   name: Get the output time
            run: echo "The time was ${{ steps.hello.outputs.time }}"
    
    deploy:
        runs-on: ubuntu-latest
        name: testing gh-pages deploy
        steps:
        -   name: Checkout
            uses: actions/checkout@master

        -   name: Build and deploy
            uses: Saw-mon-and-Natalie/gh-pages-deployment-action@v1.0.4
            env:
                ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BASE_BRANCH: master
                BRANCH: gh-pages
                FOLDER: dist
                BUILD_SCRIPT: "ls -la / && ls -la ../ && echo \"$PWD\" && . ./script.sh"
